'use strict';
const trackSelect=document.getElementById('track'),status=document.getElementById('status');
let context=null,device='pc',playing=false,timer=0,sources=[];
for(let i=0;i<MUSIC_SONGS.length;i++){const option=document.createElement('option');option.value=i;option.textContent=String(i).padStart(2,'0')+' // '+MUSIC_SONGS[i].name;trackSelect.append(option)}
const names={pc:'PC SPEAKER',opl:'ADLIB OPL2',mt32:'ROLAND MT-32',sb:'SOUND BLASTER',web:'BROWSER'};
function frequency(note){return 440*Math.pow(2,(note-69)/12)}
function stop(){playing=false;clearTimeout(timer);const now=context?context.currentTime:0;for(const source of sources){try{source.stop(now+.02)}catch(_){}}sources=[];status.textContent='READY // '+names[device]}
function destination(pan=0){const gain=context.createGain();gain.gain.value=.12;if(device==='web'&&context.createStereoPanner){const p=context.createStereoPanner();p.pan.value=pan;gain.connect(p);p.connect(context.destination)}else gain.connect(context.destination);return gain}
function tone(note,channel,velocity,when,duration){
  if(device==='pc'&&channel!==0)return;const profiles={pc:['square',.15],opl:[channel===2?'square':'sine',.11],mt32:[channel===2?'square':'triangle',.10],sb:['square',.075],web:[channel===0?'sawtooth':channel===2?'square':'triangle',.085]};
  const [type,level]=profiles[device],gain=destination(device==='web'?[-.2,.25,-.35,0][channel]:0),osc=context.createOscillator();gain.gain.setValueAtTime(.0001,when);gain.gain.exponentialRampToValueAtTime(level*velocity/100,when+.01);gain.gain.exponentialRampToValueAtTime(.0001,when+duration);osc.type=type;osc.frequency.value=frequency(note);osc.connect(gain);osc.start(when);osc.stop(when+duration+.03);sources.push(osc);
  if((device==='mt32'||device==='web')&&channel===0){const layer=context.createOscillator(),lg=context.createGain();layer.type='sine';layer.frequency.value=frequency(note)*2;lg.gain.value=.025;layer.connect(lg);lg.connect(gain);layer.start(when);layer.stop(when+duration+.03);sources.push(layer)}
}
function drum(note,velocity,when){if(device==='pc')return;const osc=context.createOscillator(),gain=destination(0);osc.type=device==='opl'?'square':'sine';osc.frequency.setValueAtTime(note===36?125:note===38?205:4100,when);if(note!==42)osc.frequency.exponentialRampToValueAtTime(48,when+.11);gain.gain.setValueAtTime((note===42?.045:.12)*velocity/100,when);gain.gain.exponentialRampToValueAtTime(.0001,when+(note===42?.05:.14));osc.connect(gain);osc.start(when);osc.stop(when+.16);sources.push(osc)}
function play(){stop();if(!context)context=new(window.AudioContext||window.webkitAudioContext)();context.resume();playing=true;const song=MUSIC_SONGS[+trackSelect.value],start=context.currentTime+.05,active=new Map();for(const event of song.events){const [tick,ch,cmd,note]=event,at=start+tick/MUSIC_SCORE_HZ;if(cmd){if(ch===3)drum(note,cmd,at);else active.set(ch,{note,velocity:cmd,at})}else if(ch!==3&&active.has(ch)){const item=active.get(ch);tone(item.note,ch,item.velocity,item.at,Math.max(.03,at-item.at));active.delete(ch)}}const seconds=song.loop/MUSIC_SCORE_HZ;status.textContent='PLAYING // '+names[device]+' // '+song.name;timer=setTimeout(()=>{if(playing)play()},seconds*1000)}
for(const button of document.querySelectorAll('[data-device]'))button.addEventListener('click',()=>{stop();device=button.dataset.device;for(const other of document.querySelectorAll('[data-device]'))other.classList.toggle('active',other===button);status.textContent='READY // '+names[device]});
document.getElementById('play').addEventListener('click',play);document.getElementById('stop').addEventListener('click',stop);trackSelect.addEventListener('change',()=>{if(playing)play()});
